import { StoreCategory } from '@prisma/client';

export const COMMON_INGREDIENTS: { name: string; category: StoreCategory }[] = [
  // Frukt & grönt
  { name: 'Äpple', category: 'fruit_veg' },
  { name: 'Päron', category: 'fruit_veg' },
  { name: 'Banan', category: 'fruit_veg' },
  { name: 'Apelsin', category: 'fruit_veg' },
  { name: 'Citron', category: 'fruit_veg' },
  { name: 'Lime', category: 'fruit_veg' },
  { name: 'Mandarin', category: 'fruit_veg' },
  { name: 'Grapefrukt', category: 'fruit_veg' },
  { name: 'Kiwi', category: 'fruit_veg' },
  { name: 'Mango', category: 'fruit_veg' },
  { name: 'Ananas', category: 'fruit_veg' },
  { name: 'Avokado', category: 'fruit_veg' },
  { name: 'Persika', category: 'fruit_veg' },
  { name: 'Plommon', category: 'fruit_veg' },
  { name: 'Körsbär', category: 'fruit_veg' },
  { name: 'Vindruvor', category: 'fruit_veg' },
  { name: 'Hallon', category: 'fruit_veg' },
  { name: 'Blåbär', category: 'fruit_veg' },
  { name: 'Jordgubbar', category: 'fruit_veg' },
  { name: 'Vattenmelon', category: 'fruit_veg' },
  { name: 'Tomat', category: 'fruit_veg' },
  { name: 'Körsbärstomater', category: 'fruit_veg' },
  { name: 'Gurka', category: 'fruit_veg' },
  { name: 'Paprika', category: 'fruit_veg' },
  { name: 'Lök', category: 'fruit_veg' },
  { name: 'Rödlök', category: 'fruit_veg' },
  { name: 'Vitlök', category: 'fruit_veg' },
  { name: 'Purjolök', category: 'fruit_veg' },
  { name: 'Salladslök', category: 'fruit_veg' },
  { name: 'Morot', category: 'fruit_veg' },
  { name: 'Potatis', category: 'fruit_veg' },
  { name: 'Sötpotatis', category: 'fruit_veg' },
  { name: 'Broccoli', category: 'fruit_veg' },
  { name: 'Blomkål', category: 'fruit_veg' },
  { name: 'Grönkål', category: 'fruit_veg' },
  { name: 'Vitkål', category: 'fruit_veg' },
  { name: 'Rödkål', category: 'fruit_veg' },
  { name: 'Spenat', category: 'fruit_veg' },
  { name: 'Sallad', category: 'fruit_veg' },
  { name: 'Rucola', category: 'fruit_veg' },
  { name: 'Isbergssallad', category: 'fruit_veg' },
  { name: 'Zucchini', category: 'fruit_veg' },
  { name: 'Aubergine', category: 'fruit_veg' },
  { name: 'Pumpa', category: 'fruit_veg' },
  { name: 'Majs', category: 'fruit_veg' },
  { name: 'Ärtor', category: 'fruit_veg' },
  { name: 'Sparris', category: 'fruit_veg' },
  { name: 'Champinjoner', category: 'fruit_veg' },
  { name: 'Kantareller', category: 'fruit_veg' },
  { name: 'Shiitake', category: 'fruit_veg' },
  { name: 'Rödbeta', category: 'fruit_veg' },
  { name: 'Palsternacka', category: 'fruit_veg' },
  { name: 'Selleri', category: 'fruit_veg' },
  { name: 'Fänkål', category: 'fruit_veg' },
  { name: 'Ingefära', category: 'fruit_veg' },
  { name: 'Chili', category: 'fruit_veg' },
  { name: 'Persilja', category: 'fruit_veg' },
  { name: 'Dill', category: 'fruit_veg' },
  { name: 'Basilika', category: 'fruit_veg' },
  { name: 'Koriander', category: 'fruit_veg' },
  { name: 'Mynta', category: 'fruit_veg' },
  { name: 'Gräslök', category: 'fruit_veg' },

  // Kött & fisk
  { name: 'Kycklingfilé', category: 'meat_fish' },
  { name: 'Kycklinglår', category: 'meat_fish' },
  { name: 'Hel kyckling', category: 'meat_fish' },
  { name: 'Köttfärs', category: 'meat_fish' },
  { name: 'Nötfärs', category: 'meat_fish' },
  { name: 'Lammfärs', category: 'meat_fish' },
  { name: 'Fläskfilé', category: 'meat_fish' },
  { name: 'Fläskkarré', category: 'meat_fish' },
  { name: 'Fläskkotlett', category: 'meat_fish' },
  { name: 'Entrecôte', category: 'meat_fish' },
  { name: 'Oxfilé', category: 'meat_fish' },
  { name: 'Högrev', category: 'meat_fish' },
  { name: 'Lammkotlett', category: 'meat_fish' },
  { name: 'Bacon', category: 'meat_fish' },
  { name: 'Pancetta', category: 'meat_fish' },
  { name: 'Skinka', category: 'meat_fish' },
  { name: 'Kokt skinka', category: 'meat_fish' },
  { name: 'Falukorv', category: 'meat_fish' },
  { name: 'Chorizo', category: 'meat_fish' },
  { name: 'Salami', category: 'meat_fish' },
  { name: 'Laxfilé', category: 'meat_fish' },
  { name: 'Rökt lax', category: 'meat_fish' },
  { name: 'Gravad lax', category: 'meat_fish' },
  { name: 'Torskfilé', category: 'meat_fish' },
  { name: 'Tonfisk', category: 'meat_fish' },
  { name: 'Makrill', category: 'meat_fish' },
  { name: 'Sill', category: 'meat_fish' },
  { name: 'Sardiner', category: 'meat_fish' },
  { name: 'Räkor', category: 'meat_fish' },
  { name: 'Musslor', category: 'meat_fish' },

  // Mejeri & ägg
  { name: 'Mjölk', category: 'dairy_eggs' },
  { name: 'Ägg', category: 'dairy_eggs' },
  { name: 'Smör', category: 'dairy_eggs' },
  { name: 'Yoghurt', category: 'dairy_eggs' },
  { name: 'Kvarg', category: 'dairy_eggs' },
  { name: 'Grädde', category: 'dairy_eggs' },
  { name: 'Vispgrädde', category: 'dairy_eggs' },
  { name: 'Crème fraiche', category: 'dairy_eggs' },
  { name: 'Gräddfil', category: 'dairy_eggs' },
  { name: 'Filmjölk', category: 'dairy_eggs' },
  { name: 'Ost', category: 'dairy_eggs' },
  { name: 'Cheddar', category: 'dairy_eggs' },
  { name: 'Mozzarella', category: 'dairy_eggs' },
  { name: 'Parmesan', category: 'dairy_eggs' },
  { name: 'Fetaost', category: 'dairy_eggs' },
  { name: 'Halloumi', category: 'dairy_eggs' },
  { name: 'Brie', category: 'dairy_eggs' },
  { name: 'Ricotta', category: 'dairy_eggs' },
  { name: 'Mascarpone', category: 'dairy_eggs' },
  { name: 'Kesella', category: 'dairy_eggs' },

  // Bröd & bageri
  { name: 'Bröd', category: 'bread_bakery' },
  { name: 'Surdegsbröd', category: 'bread_bakery' },
  { name: 'Rågbröd', category: 'bread_bakery' },
  { name: 'Knäckebröd', category: 'bread_bakery' },
  { name: 'Tortilla', category: 'bread_bakery' },
  { name: 'Pitabröd', category: 'bread_bakery' },
  { name: 'Baguette', category: 'bread_bakery' },
  { name: 'Ciabatta', category: 'bread_bakery' },
  { name: 'Toast', category: 'bread_bakery' },
  { name: 'Bulle', category: 'bread_bakery' },
  { name: 'Croissant', category: 'bread_bakery' },
  { name: 'Kanelbulle', category: 'bread_bakery' },
  { name: 'Tunnbröd', category: 'bread_bakery' },

  // Frysvaror
  { name: 'Frysta grönsaker', category: 'frozen' },
  { name: 'Frysta ärtor', category: 'frozen' },
  { name: 'Frysta räkor', category: 'frozen' },
  { name: 'Fryst lax', category: 'frozen' },
  { name: 'Fryst kyckling', category: 'frozen' },
  { name: 'Fryst pizza', category: 'frozen' },
  { name: 'Frysta bär', category: 'frozen' },
  { name: 'Glass', category: 'frozen' },

  // Konserver & torrvaror
  { name: 'Pasta', category: 'canned_dry' },
  { name: 'Spaghetti', category: 'canned_dry' },
  { name: 'Penne', category: 'canned_dry' },
  { name: 'Tagliatelle', category: 'canned_dry' },
  { name: 'Ris', category: 'canned_dry' },
  { name: 'Basmatiris', category: 'canned_dry' },
  { name: 'Jasminris', category: 'canned_dry' },
  { name: 'Nudlar', category: 'canned_dry' },
  { name: 'Glasnudlar', category: 'canned_dry' },
  { name: 'Röda linser', category: 'canned_dry' },
  { name: 'Gröna linser', category: 'canned_dry' },
  { name: 'Kikärtor', category: 'canned_dry' },
  { name: 'Svarta bönor', category: 'canned_dry' },
  { name: 'Kidneybönor', category: 'canned_dry' },
  { name: 'Vita bönor', category: 'canned_dry' },
  { name: 'Tomatkross', category: 'canned_dry' },
  { name: 'Tomatpuré', category: 'canned_dry' },
  { name: 'Kokosmjölk', category: 'canned_dry' },
  { name: 'Passata', category: 'canned_dry' },
  { name: 'Vetemjöl', category: 'canned_dry' },
  { name: 'Socker', category: 'canned_dry' },
  { name: 'Salt', category: 'canned_dry' },
  { name: 'Svartpeppar', category: 'canned_dry' },
  { name: 'Olivolja', category: 'canned_dry' },
  { name: 'Rapsolja', category: 'canned_dry' },
  { name: 'Sesamolja', category: 'canned_dry' },
  { name: 'Balsamvinäger', category: 'canned_dry' },
  { name: 'Vitvinsvinäger', category: 'canned_dry' },
  { name: 'Soja', category: 'canned_dry' },
  { name: 'Fisksås', category: 'canned_dry' },
  { name: 'Senap', category: 'canned_dry' },
  { name: 'Dijonsenap', category: 'canned_dry' },
  { name: 'Ketchup', category: 'canned_dry' },
  { name: 'Sriracha', category: 'canned_dry' },
  { name: 'Majonnäs', category: 'canned_dry' },
  { name: 'Buljong', category: 'canned_dry' },
  { name: 'Grönsaksbuljong', category: 'canned_dry' },
  { name: 'Bakpulver', category: 'canned_dry' },
  { name: 'Jäst', category: 'canned_dry' },
  { name: 'Honung', category: 'canned_dry' },
  { name: 'Lönnsirap', category: 'canned_dry' },
  { name: 'Kanel', category: 'canned_dry' },
  { name: 'Paprikapulver', category: 'canned_dry' },
  { name: 'Spiskummin', category: 'canned_dry' },
  { name: 'Gurkmeja', category: 'canned_dry' },
  { name: 'Oregano', category: 'canned_dry' },
  { name: 'Timjan', category: 'canned_dry' },
  { name: 'Rosmarin', category: 'canned_dry' },
  { name: 'Havregry', category: 'canned_dry' },
  { name: 'Müsli', category: 'canned_dry' },
  { name: 'Solrosfrön', category: 'canned_dry' },
  { name: 'Sesamfrön', category: 'canned_dry' },
  { name: 'Jordnötssmör', category: 'canned_dry' },

  // Snacks & godis
  { name: 'Chips', category: 'snacks_sweets' },
  { name: 'Popcorn', category: 'snacks_sweets' },
  { name: 'Choklad', category: 'snacks_sweets' },
  { name: 'Godis', category: 'snacks_sweets' },
  { name: 'Kex', category: 'snacks_sweets' },
  { name: 'Nötter', category: 'snacks_sweets' },
  { name: 'Mandel', category: 'snacks_sweets' },
  { name: 'Cashewnötter', category: 'snacks_sweets' },
  { name: 'Jordnötter', category: 'snacks_sweets' },
  { name: 'Müslibar', category: 'snacks_sweets' },

  // Drycker
  { name: 'Juice', category: 'beverages' },
  { name: 'Apelsinjuice', category: 'beverages' },
  { name: 'Kaffe', category: 'beverages' },
  { name: 'Te', category: 'beverages' },
  { name: 'Mineralvatten', category: 'beverages' },
  { name: 'Läsk', category: 'beverages' },
  { name: 'Öl', category: 'beverages' },
  { name: 'Vin', category: 'beverages' },
  { name: 'Rödvin', category: 'beverages' },
  { name: 'Vitvin', category: 'beverages' },
  { name: 'Cider', category: 'beverages' },
  { name: 'Saft', category: 'beverages' },

  // Städ & rengöring
  { name: 'Diskmedel', category: 'cleaning' },
  { name: 'Diskmaskinspulver', category: 'cleaning' },
  { name: 'Disktablett', category: 'cleaning' },
  { name: 'Tvättmedel', category: 'cleaning' },
  { name: 'Tvättkapsel', category: 'cleaning' },
  { name: 'Sköljmedel', category: 'cleaning' },
  { name: 'Allrengöring', category: 'cleaning' },
  { name: 'Hushållspapper', category: 'cleaning' },
  { name: 'Soppåsar', category: 'cleaning' },
  { name: 'Bakplåtspapper', category: 'cleaning' },
  { name: 'Aluminiumfolie', category: 'cleaning' },
  { name: 'Skursvamp', category: 'cleaning' },

  // Hygien & personvård
  { name: 'Schampo', category: 'personal_care' },
  { name: 'Balsam', category: 'personal_care' },
  { name: 'Tandkräm', category: 'personal_care' },
  { name: 'Tandborste', category: 'personal_care' },
  { name: 'Deodorant', category: 'personal_care' },
  { name: 'Tvål', category: 'personal_care' },
  { name: 'Duschkräm', category: 'personal_care' },
  { name: 'Rakhyvel', category: 'personal_care' },
  { name: 'Hudkräm', category: 'personal_care' },
];
