import { StoreCategory } from '@prisma/client';

const COMMON_INGREDIENTS_RAW: { name: string; category: StoreCategory }[] = [
  // Frukt & grönt
  { name: 'Äpple', category: 'fruit_veg' },
  { name: 'Päron', category: 'fruit_veg' },
  { name: 'Banan', category: 'fruit_veg' },
  { name: 'Apelsin', category: 'fruit_veg' },
  { name: 'Citron', category: 'fruit_veg' },
  { name: 'Lime', category: 'fruit_veg' },
  { name: 'Mandarin', category: 'fruit_veg' },
  { name: 'Grapefrukt', category: 'fruit_veg' },
  { name: 'Kiwi', category: 'fruit_veg' },
  { name: 'Mango', category: 'fruit_veg' },
  { name: 'Ananas', category: 'fruit_veg' },
  { name: 'Avokado', category: 'fruit_veg' },
  { name: 'Persika', category: 'fruit_veg' },
  { name: 'Plommon', category: 'fruit_veg' },
  { name: 'Körsbär', category: 'fruit_veg' },
  { name: 'Vindruvor', category: 'fruit_veg' },
  { name: 'Hallon', category: 'fruit_veg' },
  { name: 'Blåbär', category: 'fruit_veg' },
  { name: 'Jordgubbar', category: 'fruit_veg' },
  { name: 'Vattenmelon', category: 'fruit_veg' },
  { name: 'Tomat', category: 'fruit_veg' },
  { name: 'Körsbärstomater', category: 'fruit_veg' },
  { name: 'Gurka', category: 'fruit_veg' },
  { name: 'Paprika', category: 'fruit_veg' },
  { name: 'Lök', category: 'fruit_veg' },
  { name: 'Rödlök', category: 'fruit_veg' },
  { name: 'Vitlök', category: 'fruit_veg' },
  { name: 'Purjolök', category: 'fruit_veg' },
  { name: 'Salladslök', category: 'fruit_veg' },
  { name: 'Morot', category: 'fruit_veg' },
  { name: 'Potatis', category: 'fruit_veg' },
  { name: 'Sötpotatis', category: 'fruit_veg' },
  { name: 'Broccoli', category: 'fruit_veg' },
  { name: 'Blomkål', category: 'fruit_veg' },
  { name: 'Grönkål', category: 'fruit_veg' },
  { name: 'Vitkål', category: 'fruit_veg' },
  { name: 'Rödkål', category: 'fruit_veg' },
  { name: 'Spenat', category: 'fruit_veg' },
  { name: 'Sallad', category: 'fruit_veg' },
  { name: 'Rucola', category: 'fruit_veg' },
  { name: 'Isbergssallad', category: 'fruit_veg' },
  { name: 'Zucchini', category: 'fruit_veg' },
  { name: 'Aubergine', category: 'fruit_veg' },
  { name: 'Pumpa', category: 'fruit_veg' },
  { name: 'Majs', category: 'fruit_veg' },
  { name: 'Ärtor', category: 'fruit_veg' },
  { name: 'Sparris', category: 'fruit_veg' },
  { name: 'Champinjoner', category: 'fruit_veg' },
  { name: 'Kantareller', category: 'fruit_veg' },
  { name: 'Shiitake', category: 'fruit_veg' },
  { name: 'Rödbeta', category: 'fruit_veg' },
  { name: 'Palsternacka', category: 'fruit_veg' },
  { name: 'Selleri', category: 'fruit_veg' },
  { name: 'Fänkål', category: 'fruit_veg' },
  { name: 'Ingefära', category: 'fruit_veg' },
  { name: 'Chili', category: 'fruit_veg' },
  { name: 'Persilja', category: 'fruit_veg' },
  { name: 'Dill', category: 'fruit_veg' },
  { name: 'Basilika', category: 'fruit_veg' },
  { name: 'Koriander', category: 'fruit_veg' },
  { name: 'Mynta', category: 'fruit_veg' },
  { name: 'Gräslök', category: 'fruit_veg' },
  { name: 'Björnbär', category: 'fruit_veg' },
  { name: 'Fikon', category: 'fruit_veg' },
  { name: 'Melon', category: 'fruit_veg' },
  { name: 'Brysselkål', category: 'fruit_veg' },
  { name: 'Romanesco', category: 'fruit_veg' },
  { name: 'Rotselleri', category: 'fruit_veg' },
  { name: 'Rädisor', category: 'fruit_veg' },
  { name: 'Haricots verts', category: 'fruit_veg' },
  { name: 'Sockerärtor', category: 'fruit_veg' },
  { name: 'Kronärtskocka', category: 'fruit_veg' },
  { name: 'Portobello', category: 'fruit_veg' },
  { name: 'Jalapeño', category: 'fruit_veg' },
  { name: 'Granatäpple', category: 'fruit_veg' },
  { name: 'Rabarber', category: 'fruit_veg' },

  // Kött & fisk
  { name: 'Kycklingfilé', category: 'meat_fish' },
  { name: 'Kycklinglår', category: 'meat_fish' },
  { name: 'Hel kyckling', category: 'meat_fish' },
  { name: 'Köttfärs', category: 'meat_fish' },
  { name: 'Nötfärs', category: 'meat_fish' },
  { name: 'Lammfärs', category: 'meat_fish' },
  { name: 'Fläskfilé', category: 'meat_fish' },
  { name: 'Fläskkarré', category: 'meat_fish' },
  { name: 'Fläskkotlett', category: 'meat_fish' },
  { name: 'Entrecôte', category: 'meat_fish' },
  { name: 'Oxfilé', category: 'meat_fish' },
  { name: 'Högrev', category: 'meat_fish' },
  { name: 'Lammkotlett', category: 'meat_fish' },
  { name: 'Bacon', category: 'deli_charcuterie' },
  { name: 'Pancetta', category: 'deli_charcuterie' },
  { name: 'Skinka', category: 'deli_charcuterie' },
  { name: 'Kokt skinka', category: 'deli_charcuterie' },
  { name: 'Falukorv', category: 'deli_charcuterie' },
  { name: 'Chorizo', category: 'deli_charcuterie' },
  { name: 'Salami', category: 'deli_charcuterie' },
  { name: 'Laxfilé', category: 'meat_fish' },
  { name: 'Rökt lax', category: 'meat_fish' },
  { name: 'Gravad lax', category: 'meat_fish' },
  { name: 'Torskfilé', category: 'meat_fish' },
  { name: 'Tonfisk', category: 'meat_fish' },
  { name: 'Makrill', category: 'meat_fish' },
  { name: 'Sill', category: 'meat_fish' },
  { name: 'Sardiner', category: 'meat_fish' },
  { name: 'Räkor', category: 'meat_fish' },
  { name: 'Musslor', category: 'meat_fish' },
  { name: 'Kycklingvinge', category: 'meat_fish' },
  { name: 'Biff', category: 'meat_fish' },
  { name: 'Revbensspjäll', category: 'meat_fish' },
  { name: 'Prosciutto', category: 'deli_charcuterie' },
  { name: 'Korv', category: 'deli_charcuterie' },
  { name: 'Bratwurst', category: 'deli_charcuterie' },
  { name: 'Leverpastej', category: 'deli_charcuterie' },
  { name: 'Wienerkorv', category: 'deli_charcuterie' },
  { name: 'Serranoskinka', category: 'deli_charcuterie' },
  { name: 'Rökt skinka', category: 'deli_charcuterie' },
  { name: 'Blodpudding', category: 'deli_charcuterie' },
  { name: 'Brie', category: 'cheese' },
  { name: 'Camembert', category: 'cheese' },
  { name: 'Gorgonzola', category: 'cheese' },
  { name: 'Parmesan', category: 'cheese' },
  { name: 'Pecorino', category: 'cheese' },
  { name: 'Manchego', category: 'cheese' },
  { name: 'Gruyère', category: 'cheese' },
  { name: 'Oliver', category: 'deli_charcuterie' },
  { name: 'Svarta oliver', category: 'deli_charcuterie' },
  { name: 'Gröna oliver', category: 'deli_charcuterie' },
  { name: 'Antipasto', category: 'deli_charcuterie' },
  { name: 'Torsk', category: 'meat_fish' },
  { name: 'Hummer', category: 'meat_fish' },
  { name: 'Krabba', category: 'meat_fish' },
  { name: 'Bläckfisk', category: 'meat_fish' },
  { name: 'Ostron', category: 'meat_fish' },
  { name: 'Ansjovis', category: 'meat_fish' },

  // Mejeri & ägg
  { name: 'Mjölk', category: 'dairy_eggs' },
  { name: 'Ägg', category: 'dairy_eggs' },
  { name: 'Smör', category: 'dairy_eggs' },
  { name: 'Yoghurt', category: 'dairy_eggs' },
  { name: 'Kvarg', category: 'dairy_eggs' },
  { name: 'Grädde', category: 'dairy_eggs' },
  { name: 'Vispgrädde', category: 'dairy_eggs' },
  { name: 'Crème fraiche', category: 'dairy_eggs' },
  { name: 'Gräddfil', category: 'dairy_eggs' },
  { name: 'Filmjölk', category: 'dairy_eggs' },
  { name: 'Ost', category: 'cheese' },
  { name: 'Cheddar', category: 'cheese' },
  { name: 'Mozzarella', category: 'cheese' },
  { name: 'Fetaost', category: 'cheese' },
  { name: 'Halloumi', category: 'cheese' },
  { name: 'Ricotta', category: 'cheese' },
  { name: 'Mascarpone', category: 'cheese' },
  { name: 'Kesella', category: 'cheese' },
  { name: 'Gouda', category: 'cheese' },
  { name: 'Helmjölk', category: 'dairy_eggs' },
  { name: 'Mellanmjölk', category: 'dairy_eggs' },
  { name: 'Lättmjölk', category: 'dairy_eggs' },
  { name: 'Laktosfri mjölk', category: 'dairy_eggs' },
  { name: 'Grekisk yoghurt', category: 'dairy_eggs' },
  { name: 'Margarin', category: 'dairy_eggs' },

  // Bröd & bageri
  { name: 'Bröd', category: 'bread_bakery' },
  { name: 'Surdegsbröd', category: 'bread_bakery' },
  { name: 'Rågbröd', category: 'bread_bakery' },
  { name: 'Knäckebröd', category: 'bread_bakery' },
  { name: 'Tortilla', category: 'bread_bakery' },
  { name: 'Pitabröd', category: 'bread_bakery' },
  { name: 'Baguette', category: 'bread_bakery' },
  { name: 'Ciabatta', category: 'bread_bakery' },
  { name: 'Toast', category: 'bread_bakery' },
  { name: 'Bulle', category: 'bread_bakery' },
  { name: 'Croissant', category: 'bread_bakery' },
  { name: 'Kanelbulle', category: 'bread_bakery' },
  { name: 'Tunnbröd', category: 'bread_bakery' },
  { name: 'Limpa', category: 'bread_bakery' },
  { name: 'Focaccia', category: 'bread_bakery' },
  { name: 'Bagel', category: 'bread_bakery' },
  { name: 'Muffin', category: 'bread_bakery' },
  { name: 'Scones', category: 'bread_bakery' },
  { name: 'Kaka', category: 'bread_bakery' },
  { name: 'Tårta', category: 'bread_bakery' },

  // Frysvaror
  { name: 'Frysta grönsaker', category: 'frozen' },
  { name: 'Frysta ärtor', category: 'frozen' },
  { name: 'Frysta räkor', category: 'frozen' },
  { name: 'Fryst lax', category: 'frozen' },
  { name: 'Fryst kyckling', category: 'frozen' },
  { name: 'Fryst pizza', category: 'frozen' },
  { name: 'Frysta bär', category: 'frozen' },
  { name: 'Glass', category: 'frozen' },
  { name: 'Sorbet', category: 'frozen' },
  { name: 'Pizzabotten', category: 'frozen' },

  // Konserver & torrvaror
  { name: 'Pasta', category: 'canned_dry' },
  { name: 'Spaghetti', category: 'canned_dry' },
  { name: 'Penne', category: 'canned_dry' },
  { name: 'Tagliatelle', category: 'canned_dry' },
  { name: 'Ris', category: 'canned_dry' },
  { name: 'Basmatiris', category: 'canned_dry' },
  { name: 'Jasminris', category: 'canned_dry' },
  { name: 'Nudlar', category: 'canned_dry' },
  { name: 'Glasnudlar', category: 'canned_dry' },
  { name: 'Röda linser', category: 'canned_dry' },
  { name: 'Gröna linser', category: 'canned_dry' },
  { name: 'Kikärtor', category: 'canned_dry' },
  { name: 'Svarta bönor', category: 'canned_dry' },
  { name: 'Kidneybönor', category: 'canned_dry' },
  { name: 'Vita bönor', category: 'canned_dry' },
  { name: 'Tomatkross', category: 'canned_dry' },
  { name: 'Tomatpuré', category: 'canned_dry' },
  { name: 'Kokosmjölk', category: 'canned_dry' },
  { name: 'Passata', category: 'canned_dry' },
  { name: 'Vetemjöl', category: 'canned_dry' },
  { name: 'Socker', category: 'canned_dry' },
  { name: 'Salt', category: 'canned_dry' },
  { name: 'Svartpeppar', category: 'canned_dry' },
  { name: 'Olivolja', category: 'canned_dry' },
  { name: 'Rapsolja', category: 'canned_dry' },
  { name: 'Sesamolja', category: 'canned_dry' },
  { name: 'Balsamvinäger', category: 'canned_dry' },
  { name: 'Vitvinsvinäger', category: 'canned_dry' },
  { name: 'Soja', category: 'canned_dry' },
  { name: 'Fisksås', category: 'canned_dry' },
  { name: 'Senap', category: 'canned_dry' },
  { name: 'Dijonsenap', category: 'canned_dry' },
  { name: 'Ketchup', category: 'canned_dry' },
  { name: 'Sriracha', category: 'canned_dry' },
  { name: 'Majonnäs', category: 'canned_dry' },
  { name: 'Buljong', category: 'canned_dry' },
  { name: 'Grönsaksbuljong', category: 'canned_dry' },
  { name: 'Bakpulver', category: 'canned_dry' },
  { name: 'Jäst', category: 'canned_dry' },
  { name: 'Honung', category: 'canned_dry' },
  { name: 'Lönnsirap', category: 'canned_dry' },
  { name: 'Kanel', category: 'canned_dry' },
  { name: 'Paprikapulver', category: 'canned_dry' },
  { name: 'Spiskummin', category: 'canned_dry' },
  { name: 'Gurkmeja', category: 'canned_dry' },
  { name: 'Oregano', category: 'canned_dry' },
  { name: 'Timjan', category: 'canned_dry' },
  { name: 'Rosmarin', category: 'canned_dry' },
  { name: 'Havregryn', category: 'canned_dry' },
  { name: 'Müsli', category: 'canned_dry' },
  { name: 'Solrosfrön', category: 'canned_dry' },
  { name: 'Sesamfrön', category: 'canned_dry' },
  { name: 'Jordnötssmör', category: 'canned_dry' },
  { name: 'Fusilli', category: 'canned_dry' },
  { name: 'Linguine', category: 'canned_dry' },
  { name: 'Rigatoni', category: 'canned_dry' },
  { name: 'Ramen', category: 'canned_dry' },
  { name: 'Udon', category: 'canned_dry' },
  { name: 'Cannellinibönor', category: 'canned_dry' },
  { name: 'Edamame', category: 'canned_dry' },
  { name: 'Krossade tomater', category: 'canned_dry' },
  { name: 'Rågmjöl', category: 'canned_dry' },
  { name: 'Dinkelmjöl', category: 'canned_dry' },
  { name: 'Mandelmjöl', category: 'canned_dry' },
  { name: 'Florsocker', category: 'canned_dry' },
  { name: 'Farinsocker', category: 'canned_dry' },
  { name: 'Vitpeppar', category: 'canned_dry' },
  { name: 'Kokosolja', category: 'canned_dry' },
  { name: 'Äppelcidervinäger', category: 'canned_dry' },
  { name: 'Tamari', category: 'canned_dry' },
  { name: 'Tabasco', category: 'canned_dry' },
  { name: 'Worcestershiresås', category: 'canned_dry' },
  { name: 'Sweet chili-sås', category: 'canned_dry' },
  { name: 'Barbecuesås', category: 'canned_dry' },
  { name: 'Aioli', category: 'canned_dry' },
  { name: 'Remoulad', category: 'canned_dry' },
  { name: 'Kycklingbuljong', category: 'canned_dry' },
  { name: 'Köttbuljong', category: 'canned_dry' },
  { name: 'Bikarbonat', category: 'canned_dry' },
  { name: 'Torrjäst', category: 'canned_dry' },
  { name: 'Vaniljsocker', category: 'canned_dry' },
  { name: 'Vaniljextrakt', category: 'canned_dry' },
  { name: 'Kakao', category: 'canned_dry' },
  { name: 'Chokladpulver', category: 'canned_dry' },
  { name: 'Nutella', category: 'canned_dry' },
  { name: 'Granola', category: 'canned_dry' },
  { name: 'Cornflakes', category: 'canned_dry' },
  { name: 'Nötmix', category: 'canned_dry' },
  { name: 'Pumpakärnor', category: 'canned_dry' },
  { name: 'Chiafrön', category: 'canned_dry' },
  { name: 'Linfrön', category: 'canned_dry' },

  // Snacks & godis
  { name: 'Chips', category: 'snacks_sweets' },
  { name: 'Popcorn', category: 'snacks_sweets' },
  { name: 'Choklad', category: 'snacks_sweets' },
  { name: 'Godis', category: 'snacks_sweets' },
  { name: 'Kex', category: 'snacks_sweets' },
  { name: 'Nötter', category: 'snacks_sweets' },
  { name: 'Mandel', category: 'snacks_sweets' },
  { name: 'Cashewnötter', category: 'snacks_sweets' },
  { name: 'Jordnötter', category: 'snacks_sweets' },
  { name: 'Müslibar', category: 'snacks_sweets' },
  { name: 'Nachos', category: 'snacks_sweets' },
  { name: 'Pretzel', category: 'snacks_sweets' },
  { name: 'Lösgodis', category: 'snacks_sweets' },
  { name: 'Kola', category: 'snacks_sweets' },
  { name: 'Lakrits', category: 'snacks_sweets' },
  { name: 'Pistagenötter', category: 'snacks_sweets' },
  { name: 'Valnötter', category: 'snacks_sweets' },
  { name: 'Pekannötter', category: 'snacks_sweets' },
  { name: 'Proteinbar', category: 'snacks_sweets' },

  // Drycker
  { name: 'Juice', category: 'beverages' },
  { name: 'Apelsinjuice', category: 'beverages' },
  { name: 'Kaffe', category: 'beverages' },
  { name: 'Te', category: 'beverages' },
  { name: 'Mineralvatten', category: 'beverages' },
  { name: 'Läsk', category: 'beverages' },
  { name: 'Öl', category: 'beverages' },
  { name: 'Vin', category: 'beverages' },
  { name: 'Rödvin', category: 'beverages' },
  { name: 'Vitvin', category: 'beverages' },
  { name: 'Cider', category: 'beverages' },
  { name: 'Saft', category: 'beverages' },
  { name: 'Äppeljuice', category: 'beverages' },
  { name: 'Vatten', category: 'beverages' },
  { name: 'Kolsyrat vatten', category: 'beverages' },
  { name: 'Espresso', category: 'beverages' },
  { name: 'Grönt te', category: 'beverages' },
  { name: 'Svart te', category: 'beverages' },
  { name: 'Örtte', category: 'beverages' },
  { name: 'Cola', category: 'beverages' },
  { name: 'Fanta', category: 'beverages' },
  { name: 'Sprite', category: 'beverages' },
  { name: 'Lager', category: 'beverages' },
  { name: 'IPA', category: 'beverages' },
  { name: 'Ale', category: 'beverages' },
  { name: 'Rosé', category: 'beverages' },
  { name: 'Prosecco', category: 'beverages' },
  { name: 'Champagne', category: 'beverages' },
  { name: 'Äppelcider', category: 'beverages' },
  { name: 'Sportdryck', category: 'beverages' },
  { name: 'Energidryck', category: 'beverages' },
  { name: 'Smoothie', category: 'beverages' },
  { name: 'Kokosvatten', category: 'beverages' },

  // Städ & rengöring
  { name: 'Diskmedel', category: 'cleaning' },
  { name: 'Diskmaskinspulver', category: 'cleaning' },
  { name: 'Disktablett', category: 'cleaning' },
  { name: 'Tvättmedel', category: 'cleaning' },
  { name: 'Tvättkapsel', category: 'cleaning' },
  { name: 'Sköljmedel', category: 'cleaning' },
  { name: 'Allrengöring', category: 'cleaning' },
  { name: 'Hushållspapper', category: 'cleaning' },
  { name: 'Soppåsar', category: 'cleaning' },
  { name: 'Bakplåtspapper', category: 'cleaning' },
  { name: 'Aluminiumfolie', category: 'cleaning' },
  { name: 'Skursvamp', category: 'cleaning' },
  { name: 'Torkmedel', category: 'cleaning' },
  { name: 'WC-rengöring', category: 'cleaning' },
  { name: 'Plastfolie', category: 'cleaning' },
  { name: 'Papperspåsar', category: 'cleaning' },

  // Hygien & personvård
  { name: 'Schampo', category: 'personal_care' },
  { name: 'Balsam', category: 'personal_care' },
  { name: 'Tandkräm', category: 'personal_care' },
  { name: 'Tandborste', category: 'personal_care' },
  { name: 'Deodorant', category: 'personal_care' },
  { name: 'Tvål', category: 'personal_care' },
  { name: 'Duschkräm', category: 'personal_care' },
  { name: 'Rakhyvel', category: 'personal_care' },
  { name: 'Hudkräm', category: 'personal_care' },
  { name: 'Hårinpackning', category: 'personal_care' },
  { name: 'Tandtråd', category: 'personal_care' },
  { name: 'Munskölj', category: 'personal_care' },
  { name: 'Handtvål', category: 'personal_care' },
  { name: 'Rakskum', category: 'personal_care' },
  { name: 'Lotion', category: 'personal_care' },
  { name: 'Solskydd', category: 'personal_care' },
  { name: 'Tamponger', category: 'personal_care' },
  { name: 'Bindor', category: 'personal_care' },
  { name: 'Paracetamol', category: 'personal_care' },
  { name: 'Ibuprofen', category: 'personal_care' },
  { name: 'Vitaminer', category: 'personal_care' },
  { name: 'Plåster', category: 'personal_care' },
];

export const COMMON_INGREDIENTS: { name: string; category: StoreCategory }[] =
  COMMON_INGREDIENTS_RAW.map(i => ({ ...i, name: i.name.toLowerCase() }));
